[package]
name = "demo-07-bma223"
version = "0.1.0"
authors = ["Alvin Wong <alvinhochun@gmail.com>"]
edition = "2018"

[dependencies]
embedded-hal = "0.2.4"
gd32vf103-pac = "0.4"
gd32vf103xx-hal = "0.4"
nb = "1.0"
panic-halt = "0.2.0"
riscv-rt = "0.8"
